// Mocks generated by Mockito 5.0.16 from annotations
// in prova_avonale/test/modules/movie_api/data/repositories/movies_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prova_avonale/modules/movie_api/data/datasources/movies_remote_datasource.dart'
    as _i3;
import 'package:prova_avonale/modules/movie_api/data/models/movie_details_model.dart'
    as _i2;
import 'package:prova_avonale/modules/movie_api/data/models/movie_search_model.dart'
    as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMovieDetailsModel_0 extends _i1.Fake
    implements _i2.MovieDetailsModel {}

/// A class which mocks [IMoviesRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMoviesRemoteDatasource extends _i1.Mock
    implements _i3.IMoviesRemoteDatasource {
  MockIMoviesRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.MovieSearchModel>> getPopularMovies() =>
      (super.noSuchMethod(Invocation.method(#getPopularMovies, []),
              returnValue: Future<List<_i5.MovieSearchModel>>.value(
                  <_i5.MovieSearchModel>[]))
          as _i4.Future<List<_i5.MovieSearchModel>>);
  @override
  _i4.Future<List<_i5.MovieSearchModel>> searchMovies(String? keyword) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [keyword]),
              returnValue: Future<List<_i5.MovieSearchModel>>.value(
                  <_i5.MovieSearchModel>[]))
          as _i4.Future<List<_i5.MovieSearchModel>>);
  @override
  _i4.Future<_i2.MovieDetailsModel> getMovieDetails(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetails, [id]),
              returnValue: Future<_i2.MovieDetailsModel>.value(
                  _FakeMovieDetailsModel_0()))
          as _i4.Future<_i2.MovieDetailsModel>);
  @override
  String toString() => super.toString();
}
