// Mocks generated by Mockito 5.0.16 from annotations
// in prova_avonale/test/modules/movie_api/domain/usecases/get_movie_details_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:prova_avonale/modules/movie_api/domain/entities/movie_details_entity.dart'
    as _i7;
import 'package:prova_avonale/modules/movie_api/domain/entities/movie_search_entity.dart'
    as _i6;
import 'package:prova_avonale/modules/movie_api/domain/repositories/movies_repository_interface.dart'
    as _i3;
import 'package:prova_avonale/shared/errors/failures_error.dart' as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [IMoviesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMoviesRepository extends _i1.Mock implements _i3.IMoviesRepository {
  MockIMoviesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.FailureError, List<_i6.MovieSearchEntity>>>
      getPopularMovies() => (super.noSuchMethod(
          Invocation.method(#getPopularMovies, []),
          returnValue:
              Future<_i2.Either<_i5.FailureError, List<_i6.MovieSearchEntity>>>.value(
                  _FakeEither_0<_i5.FailureError,
                      List<_i6.MovieSearchEntity>>())) as _i4
          .Future<_i2.Either<_i5.FailureError, List<_i6.MovieSearchEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.FailureError, List<_i6.MovieSearchEntity>>>
      searchMovie(String? keyword) => (super.noSuchMethod(
          Invocation.method(#searchMovie, [keyword]),
          returnValue:
              Future<_i2.Either<_i5.FailureError, List<_i6.MovieSearchEntity>>>.value(
                  _FakeEither_0<_i5.FailureError,
                      List<_i6.MovieSearchEntity>>())) as _i4
          .Future<_i2.Either<_i5.FailureError, List<_i6.MovieSearchEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.FailureError, _i7.MovieDetailsEntity>>
      getMovieDetails(int? idMovie) => (super.noSuchMethod(
          Invocation.method(#getMovieDetails, [idMovie]),
          returnValue: Future<
                  _i2.Either<_i5.FailureError, _i7.MovieDetailsEntity>>.value(
              _FakeEither_0<_i5.FailureError, _i7.MovieDetailsEntity>())) as _i4
          .Future<_i2.Either<_i5.FailureError, _i7.MovieDetailsEntity>>);
  @override
  String toString() => super.toString();
}
